# Generated by Django 5.1.7 on 2025-04-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missatge',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges', to='alerts_chat.chat'),
        ),
        migrations.AddField(
            model_name='missatge',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges_enviats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puntemergencia',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='alerts_chat.puntemergencia'),
        ),
    ]
