# Generated by Django 5.1.7 on 2025-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntemergencia',
            name='id_emergencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
