# Generated by Django 5.1.7 on 2025-04-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missatge',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
