# Generated by Django 5.1.6 on 2025-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='num_spots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
