# Generated by Django 5.1.7 on 2025-05-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('cross_street', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('is_charging_station', models.BooleanField()),
                ('ride_code_support', models.BooleanField(default=False)),
                ('nearby_distance', models.FloatField(blank=True, null=True)),
                ('physical_configuration', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
