# Generated by Django 5.1.7 on 2025-05-18 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('is_charging_station', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UltimaActualizacionBicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('fecha_llamada', models.DateTimeField()),
                ('fecha_actualizacion_api', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadEstacionBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bicis_disponibles', models.IntegerField(default=0)),
                ('num_bicis_mecanicas', models.IntegerField(default=0)),
                ('num_bicis_electricas', models.IntegerField(default=0)),
                ('num_docks_disponibles', models.IntegerField(default=0)),
                ('estado', models.CharField(default='IN_SERVICE', max_length=50)),
                ('estacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='estaciones_bici.estacionbici')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bicicleta', models.CharField(choices=[('mecanica', 'Mecánica'), ('electrica', 'Eléctrica')], max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estaciones_bici.estacionbici')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
