name: Django CI

# Run this every time a push or pull request is made
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test: # Name of the job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Pull the repo into the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django check
        run: |
          python manage.py check

      - name: Check for missing migrations
        run: |
          python manage.py makemigrations --check --dry-run

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
