name: Mirror to FIB GitLab

on:
  push:
    branches:
      - develop  # Ahora se activará cuando haya un push a la rama develop

jobs:
  push-to-fib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Set up SSH
      if: secrets.FIB_SSH_KEY != ''
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.FIB_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan repo.fib.upc.edu >> ~/.ssh/known_hosts

    - name: Push to FIB repo
      run: |
        git remote add fib "${{ secrets.FIB_REPO_URL }}"
        git push fib HEAD:develop --force
