# Generated by Django 5.1.6 on 2025-04-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punt',
            fields=[
                ('id_punt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('direccio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipusCarregador',
            fields=[
                ('id_carregador', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_tipus', models.CharField(max_length=100)),
                ('tipus_connector', models.CharField(max_length=100)),
                ('tipus_corrent', models.CharField(choices=[('AC', 'Corrent alterna'), ('DC', 'Corrent continua')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstacioCarrega',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_punts_carrega.punt')),
                ('gestio', models.CharField(max_length=100)),
                ('tipus_acces', models.CharField(max_length=100)),
                ('nplaces', models.CharField(max_length=20, null=True)),
                ('potencia', models.IntegerField(null=True)),
                ('tipus_velocitat', models.CharField(choices=[('LENTA', 'Càrrega lenta'), ('SEMI_RAPIDA', 'Càrrega semi-ràpida'), ('RAPIDA', 'Càrrega ràpida'), ('ULTRA_RAPIDA', 'Càrrega ultra-ràpida')], max_length=100, null=True)),
                ('tipus_carregador', models.ManyToManyField(related_name='estacions_de_carrega', to='api_punts_carrega.tipuscarregador')),
            ],
            bases=('api_punts_carrega.punt',),
        ),
        migrations.CreateModel(
            name='ModelCotxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('any_model', models.IntegerField()),
                ('tipus_carregador', models.ManyToManyField(related_name='tipus_carregador', to='api_punts_carrega.tipuscarregador')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('carrega_actual', models.FloatField()),
                ('Capacitat_bateria', models.FloatField()),
                ('Model_cotxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api_punts_carrega.modelcotxe')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.DurationField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api_punts_carrega.estaciocarrega')),
            ],
        ),
    ]
