# Generated by Django 5.1.7 on 2025-04-15 08:50

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punt',
            fields=[
                ('id_punt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('direccio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.DurationField(help_text='Reserva mínima 15 min, Reserva máxima 24 h', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=900)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
            ],
        ),
        migrations.CreateModel(
            name='TipusCarregador',
            fields=[
                ('id_carregador', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom_tipus', models.CharField(max_length=100)),
                ('tipus_connector', models.CharField(max_length=100)),
                ('tipus_corrent', models.CharField(choices=[('Corrent alterna', 'Ac'), ('Corrent continua', 'Dc')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('idioma', models.CharField(choices=[('Català', 'Catala'), ('Castellano', 'Castellano'), ('English', 'English')], default='Català', max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DataDescompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_obtencio', models.DateField()),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descomptes_obtinguts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descomptes',
            fields=[
                ('id_descompte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('punts_necessaris', models.IntegerField()),
                ('usuaris', models.ManyToManyField(related_name='descomptes', through='api_punts_carrega.DataDescompte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datadescompte',
            name='descompte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuaris_obtenidors', to='api_punts_carrega.descomptes'),
        ),
        migrations.CreateModel(
            name='EstacioCarrega',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_punts_carrega.punt')),
                ('gestio', models.CharField(max_length=100)),
                ('tipus_acces', models.CharField(max_length=100)),
                ('nplaces', models.CharField(max_length=20, null=True)),
                ('potencia', models.IntegerField(null=True)),
                ('tipus_velocitat', models.CharField(choices=[('Càrrega lenta', 'Lenta'), ('Càrrega semi-ràpida', 'Semi Rapida'), ('Càrrega ràpida', 'Rapida'), ('Càrrega ultra-ràpida', 'Ultra Rapida')], max_length=100, null=True)),
                ('tipus_carregador', models.ManyToManyField(related_name='estacions_de_carrega', to='api_punts_carrega.tipuscarregador')),
            ],
            bases=('api_punts_carrega.punt',),
        ),
        migrations.CreateModel(
            name='RefugioClimatico',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_punts_carrega.punt')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_calle', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('api_punts_carrega.punt',),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('missatge', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('administrador_assignat', models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assignats', to=settings.AUTH_USER_MODEL)),
                ('reportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_emesos', to=settings.AUTH_USER_MODEL)),
                ('reportat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_rebuts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaFinalitzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punts_obtinguts', models.IntegerField(default=0)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finalitzada', to='api_punts_carrega.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucio', models.CharField(choices=[('Usuari bloquejat', 'Usuari Bloquejat'), ('Missatge eliminat', 'Missatge Eliminat'), ('Absolt', 'Absolt')], max_length=50)),
                ('missatge', models.TextField()),
                ('data_resolucio', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='api_punts_carrega.report')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCotxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('any_model', models.IntegerField()),
                ('tipus_carregador', models.ManyToManyField(related_name='tipus_carregador', to='api_punts_carrega.tipuscarregador')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuat', models.IntegerField(help_text='Valoració entre 1 i 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ressenya', models.TextField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoracio', to='api_punts_carrega.reservafinalitzada')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('carrega_actual', models.FloatField()),
                ('capacitat_bateria', models.FloatField()),
                ('model_cotxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api_punts_carrega.modelcotxe')),
                ('propietari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='datadescompte',
            unique_together={('usuari', 'descompte')},
        ),
        migrations.AddField(
            model_name='reserva',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api_punts_carrega.estaciocarrega'),
        ),
        migrations.CreateModel(
            name='PuntEmergencia',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_punts_carrega.punt')),
                ('titol', models.CharField(max_length=100)),
                ('descripcio', models.TextField()),
                ('actiu', models.BooleanField(default=True)),
                ('data_creacio', models.DateField(auto_now_add=True)),
                ('creat_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punts_emergencia_creats', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api_punts_carrega.punt',),
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id_missatge', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('missatge', models.TextField()),
                ('data', models.DateField()),
                ('llegit', models.BooleanField(default=False)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges', to=settings.AUTH_USER_MODEL)),
                ('punt_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missatges', to='api_punts_carrega.puntemergencia')),
            ],
        ),
    ]
