# Generated by Django 5.1.7 on 2025-04-15 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntemergencia',
            name='id_emergencia',
        ),
        migrations.RemoveField(
            model_name='puntemergencia',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='puntemergencia',
            name='lng',
        ),
        migrations.AddField(
            model_name='puntemergencia',
            name='creat_per',
            field=models.ForeignKey(default=231299, on_delete=django.db.models.deletion.CASCADE, related_name='punts_emergencia_creats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntemergencia',
            name='data_creacio',
            field=models.DateField(auto_now_add=True, default=231299),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntemergencia',
            name='punt_ptr',
            field=models.OneToOneField(auto_created=True, default=231299, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_punts_carrega.punt'),
            preserve_default=False,
        ),
    ]
