# Generated by Django 5.1.7 on 2025-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Vehicles',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='api_punts_carrega.vehicle'),
        ),
    ]
