# Generated by Django 5.1.6 on 2025-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntemergencia',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
