# Generated by Django 5.2.1 on 2025-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostareport',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='RespostaReport',
        ),
    ]
