# Generated by Django 4.2.20 on 2025-03-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estacio',
            new_name='estacion',
        ),
    ]
