# Generated by Django 5.1.7 on 2025-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_es', models.TextField(blank=True, null=True)),
                ('text_ca', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
