# Generated by Django 5.1.6 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces_lliures',
            field=models.FloatField(null=True),
        ),
    ]
