# Generated by Django 5.1.6 on 2025-03-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='puntcarrega',
            constraint=models.UniqueConstraint(fields=('estacio', 'id_punt_carrega'), name='unique_p_carrega'),
        ),
    ]
