# Generated by Django 5.1.6 on 2025-03-23 12:36

import api_punts_carrega.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipuscarregador',
            name='punt_carrega',
        ),
        migrations.AddField(
            model_name='estaciocarrega',
            name='potencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='estaciocarrega',
            name='tipus_carregador',
            field=models.ManyToManyField(related_name='estacions_de_carrega', to='api_punts_carrega.tipuscarregador'),
        ),
        migrations.AddField(
            model_name='estaciocarrega',
            name='tipus_velocitat',
            field=models.CharField(choices=[('LENTA', api_punts_carrega.models.Velocitat_de_carrega['LENTA']), ('SEMI_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['SEMI_RAPIDA']), ('RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['RAPIDA']), ('ULTRA_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['ULTRA_RAPIDA'])], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PuntCarrega',
        ),
    ]
