# Generated by Django 5.1.6 on 2025-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0002_alter_estaciocarrega_nplaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces_lliures',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
