# Generated by Django 5.1.6 on 2025-03-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0002_puntcarrega_unique_p_carrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punt',
            name='ubicacio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punt', to='api_punts_carrega.ubicacio'),
        ),
    ]
