# Generated by Django 5.1.6 on 2025-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0002_remove_tipuscarregador_punt_carrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaciocarrega',
            name='nplaces_lliures',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
