# Generated by Django 5.2.1 on 2025-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0002_remove_respostareport_report_delete_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
