# Generated by Django 5.1.6 on 2025-03-10 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0003_alter_punt_ubicacio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punt',
            old_name='ubicacio',
            new_name='ubicacio_punt',
        ),
        migrations.AddField(
            model_name='estaciocarrega',
            name='ubicacio_estacio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estaciocarrega', to='api_punts_carrega.ubicacio'),
        ),
    ]
