# Generated by Django 5.1.6 on 2025-03-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0003_estaciocarrega_nplaces_lliures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCotxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('any_model', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('carrega_actual', models.FloatField()),
                ('Capacitat_bateria', models.FloatField()),
                ('Model_cotxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api_punts_carrega.modelcotxe')),
            ],
        ),
    ]
