# Generated by Django 5.1.7 on 2025-03-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0003_alter_estaciocarrega_nplaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estaciocarrega',
            name='nplaces_lliures',
        ),
    ]
