# Generated by Django 5.1.7 on 2025-05-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idioma',
            field=models.CharField(choices=[('Catala', 'Catala'), ('Castellano', 'Castellano'), ('English', 'English')], default='Catala', max_length=20),
        ),
    ]
