# Generated by Django 5.1.6 on 2025-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0004_rename_ubicacio_punt_ubicacio_punt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.CharField(max_length=50, unique=True)),
                ('description_location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('power_kw', models.FloatField(blank=True, null=True)),
                ('speed_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('current_type', models.CharField(blank=True, max_length=20, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_spots', models.TextField(blank=True, null=True)),
                ('access_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
