# Generated by Django 5.1.6 on 2025-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0005_chargingstation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingStation',
        ),
    ]
