# Generated by Django 5.1.6 on 2025-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0006_delete_chargingstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='estaciocarrega',
            name='nplaces',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
