# Generated by Django 5.1.6 on 2025-03-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0007_estaciocarrega_nplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='ubicacio_estacio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estaciocarrega', to='api_punts_carrega.ubicacio'),
        ),
    ]
