# Generated by Django 5.1.6 on 2025-03-17 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0008_alter_estaciocarrega_ubicacio_estacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inici', models.DateTimeField()),
                ('hora_fi', models.DateTimeField()),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('estacio_carrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_punts_carrega.estaciocarrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
