# Generated by Django 5.1.6 on 2025-03-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0008_alter_estaciocarrega_ubicacio_estacio'),
    ]

    operations = [
    ]
