# Generated by Django 5.1.6 on 2025-03-18 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0008_alter_estaciocarrega_ubicacio_estacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punt',
            name='ubicacio_punt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punt', to='api_punts_carrega.ubicacio'),
        ),
    ]
