# Generated by Django 5.1.6 on 2025-03-18 10:42

import api_punts_carrega.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0009_alter_punt_ubicacio_punt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntcarrega',
            name='tipus_velocitat',
            field=models.CharField(choices=[('LENTA', api_punts_carrega.models.Velocitat_de_carrega['LENTA']), ('SEMI_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['SEMI_RAPIDA']), ('RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['RAPIDA']), ('ULTRA_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['ULTRA_RAPIDA'])], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipuscarregador',
            name='tipus_corrent',
            field=models.CharField(choices=[('AC', api_punts_carrega.models.Tipus_de_Corrent['AC']), ('DC', api_punts_carrega.models.Tipus_de_Corrent['DC'])], max_length=100),
        ),
    ]
