# Generated by Django 5.1.6 on 2025-03-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0009_auto_20250318_1758'),
    ]

    operations = [
    ]
