# Generated by Django 5.1.6 on 2025-03-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0010_auto_20250318_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='ubicacio_estacio',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AlterField(
            model_name='punt',
            name='ubicacio_punt',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
    ]
