# Generated by Django 5.1.6 on 2025-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0010_alter_puntcarrega_tipus_velocitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='tipus_acces',
            field=models.CharField(max_length=100),
        ),
    ]
