# Generated by Django 5.1.6 on 2025-03-19 10:08

import api_punts_carrega.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0011_alter_estaciocarrega_ubicacio_estacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estaciocarrega',
            name='tipus_acces',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puntcarrega',
            name='tipus_velocitat',
            field=models.CharField(choices=[('LENTA', api_punts_carrega.models.Velocitat_de_carrega['LENTA']), ('SEMI_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['SEMI_RAPIDA']), ('RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['RAPIDA']), ('ULTRA_RAPIDA', api_punts_carrega.models.Velocitat_de_carrega['ULTRA_RAPIDA'])], max_length=100),
        ),
    ]
