# Generated by Django 5.1.6 on 2025-03-19 10:52

import api_punts_carrega.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0012_alter_estaciocarrega_nplaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciocarrega',
            name='nplaces',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estaciocarrega',
            name='ubicacio_estacio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estaciocarrega', to='api_punts_carrega.ubicacio'),
        ),
        migrations.AlterField(
            model_name='punt',
            name='ubicacio_punt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punt', to='api_punts_carrega.ubicacio'),
        ),
        migrations.AlterField(
            model_name='tipuscarregador',
            name='tipus_corrent',
            field=models.CharField(choices=[('AC', api_punts_carrega.models.Tipus_de_Corrent['AC']), ('DC', api_punts_carrega.models.Tipus_de_Corrent['DC'])], max_length=100),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inici', models.DateTimeField()),
                ('hora_fi', models.DateTimeField()),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('estacio_carrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_punts_carrega.estaciocarrega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
