# Generated by Django 5.1.6 on 2025-03-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0011_alter_estaciocarrega_tipus_acces'),
        ('api_punts_carrega', '0013_alter_estaciocarrega_nplaces_and_more'),
    ]

    operations = [
    ]
