# Generated by Django 5.1.6 on 2025-03-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0009_reserva'),
        ('api_punts_carrega', '0014_merge_20250319_1727'),
    ]

    operations = [
    ]
