# Generated by Django 5.1.6 on 2025-03-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_punts_carrega', '0015_merge_0009_reserva_0014_merge_20250319_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntcarrega',
            name='id_punt_carrega',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
